# Generated by Django 5.1.1 on 2024-09-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='portafolio/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
