# Generated by Django 5.1.1 on 2024-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
