# Generated by Django 5.1.1 on 2024-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_proyecto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
