# Generated by Django 5.1.1 on 2024-10-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_proyecto_img2_proyecto_img3_proyecto_img4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='habilidades',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
