# Generated by Django 5.1.1 on 2024-10-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_proyecto_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='habilidades',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
