# Generated by Django 5.1.1 on 2024-10-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_alter_proyecto_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='desc',
            field=models.CharField(max_length=400),
        ),
    ]
